--DBT AUTOMATION has generated this model, please DO NOT EDIT 
--Please make sure you dont change the model name 

{{ config(materialized='table', schema='production') }}
WITH cte2 as (

SELECT "t1"."_airbyte_raw_id",
"t1"."_airbyte_extracted_at",
"t1"."_airbyte_meta",
"t1"."_airbyte_generation_id",
"t1"."sex_raw",
"t1"."area_raw",
"t1"."ward_raw",
"t1"."notes_raw",
"t1"."state_raw",
"t1"."entered_by",
"t1"."child_id_raw",
"t1"."district_raw",
"t1"."severity_raw",
"t1"."diagnosis_raw",
"t1"."mother_id_raw",
"t1"."source_row_id",
"t1"."age_months_raw",
"t1"."child_name_raw",
"t1"."visit_date_raw",
"t1"."case_status_raw",
"t1"."partner_ngo_raw",
"t1"."tracking_id_raw",
"t1"."household_id_raw",
"t1"."social_score_raw",
"t1"."school_status_raw",
"t1"."screening_tool_raw",
"t1"."assistive_device_raw",
"t1"."fine_motor_score_raw",
"t1"."next_review_date_raw",
"t1"."therapy_referred_raw",
"t1"."gross_motor_score_raw",
"t1"."synthetic_record_flag",
"t1"."home_program_given_raw",
"t1"."communication_score_raw",
"t1"."caregiver_beneficiary_id_raw",
"t1"."linked_clinic_meeting_id_raw",
"t1"."sessions_attended_last_month_raw",
"t1"."sex_case_demo",
"t1"."age_months_source",
"t1"."age_months_clean",
"t1"."area",
"t1"."ward",
"t1"."state",
"t1"."district",
"t1"."child_id",
"t1"."child_name",
"t1"."mother_id",
"t1"."household_id",
"t1"."caregiver_beneficiary_id",
"t1"."partner_ngo",
"t1"."tracking_id",
"t1"."sex_clean",
"t1"."sex",
"t1"."severity_source",
"t1"."severity",
"t1"."diagnosis_source",
"t1"."diagnosis",
"t1"."therapy_referral_source",
"t1"."therapy_referral",
"t1"."therapy_referred_text",
"t1"."case_status_source",
"t1"."case_status",
"t1"."screening_tool_source",
"t1"."screening_tool",
"t1"."school_status_source",
"t1"."school_status",
"t1"."social_score_source",
"t1"."fine_motor_score_source",
"t1"."gross_motor_score_source",
"t1"."communication_score_source",
"t1"."sessions_attended_source",
"t1"."next_review_date_source",
"t1"."visit_date_source",
"t1"."visit_date_clean1",
"t1"."visit_date_text",
"t1"."visit_date",
"t2"."_airbyte_raw_id" AS "_airbyte_raw_id_2",
"t2"."_airbyte_extracted_at" AS "_airbyte_extracted_at_2",
"t2"."_airbyte_meta" AS "_airbyte_meta_2",
"t2"."_airbyte_generation_id" AS "_airbyte_generation_id_2",
"t2"."age_raw",
"t2"."sex_raw" AS "sex_raw_2",
"t2"."notes_raw" AS "notes_raw_2",
"t2"."state_raw" AS "state_raw_2",
"t2"."entered_by" AS "entered_by_2",
"t2"."status_raw",
"t2"."child_id_raw" AS "child_id_raw_2",
"t2"."district_raw" AS "district_raw_2",
"t2"."encounter_id",
"t2"."doctor_id_raw",
"t2"."source_row_id" AS "source_row_id_2",
"t2"."meeting_id_raw",
"t2"."speciality_raw",
"t2"."clinic_site_raw",
"t2"."doctor_name_raw",
"t2"."partner_ngo_raw" AS "partner_ngo_raw_2",
"t2"."action_taken_raw",
"t2"."household_id_raw" AS "household_id_raw_2",
"t2"."last_updated_raw",
"t2"."meeting_date_raw",
"t2"."meeting_type_raw",
"t2"."patient_name_raw",
"t2"."duration_mins_raw",
"t2"."beneficiary_id_raw",
"t2"."follow_up_date_raw",
"t2"."referral_source_raw",
"t2"."reason_for_visit_raw",
"t2"."synthetic_record_flag" AS "synthetic_record_flag_2",
"t2"."meeting_start_time_raw",
"t2"."diagnosis_or_concern_raw",
"t2"."status_case_demo",
"t2"."status",
"t2"."beneficiary_id",
"t2"."meeting_id",
"t2"."clinic_site",
"t2"."follow_up_date",
"t2"."state" AS "state_2",
"t2"."district" AS "district_2",
"t2"."sex" AS "sex_2",
"t2"."meeting_type",
"t2"."meeting_date_text",
"t2"."meeting_date"
 FROM {{ref('mart_health_child_development')}} t1
 LEFT JOIN {{ref('mart_health_clinic_delivery')}} t2
 ON "t1"."linked_clinic_meeting_id_raw" = "t2"."meeting_id"
) , cte1 as (
SELECT DISTINCT ON (tracking_id) *  FROM cte2)
-- Final SELECT statement combining the outputs of all CTEs
SELECT *
FROM cte1