select
    clinic.clinic_meeting_row_sk,
    clinic.meeting_id,
    clinic.encounter_id,
    clinic.meeting_date,
    date_trunc('month', clinic.meeting_date)::date as meeting_month,
    clinic.follow_up_date,
    clinic.last_updated_date,
    clinic.clinic_site,
    clinic.doctor_id,
    clinic.doctor_name,
    clinic.specialty,
    clinic.meeting_type,
    clinic.meeting_status,
    clinic.is_completed,
    clinic.has_follow_up,
    clinic.child_id,
    clinic.beneficiary_id,
    clinic.household_id,
    households.district,
    households.ward,
    households.area,
    clinic.patient_name,
    clinic.age_months,
    clinic.age_years,
    clinic.sex,
    clinic.referral_source,
    clinic.reason_for_visit,
    clinic.diagnosis_or_concern,
    clinic.action_taken,
    clinic.duration_minutes,
    clinic.entered_by,
    clinic.source_loaded_at
from {{ ref('stg_health__clinic_meetings') }} as clinic
left join {{ ref('dim_health_households') }} as households
    on clinic.household_id = households.household_id
where not clinic.is_duplicate_meeting_id
