select
    chatbot.chatbot_interaction_row_sk,
    chatbot.interaction_id,
    chatbot.session_id,
    chatbot.interaction_date,
    date_trunc('month', chatbot.interaction_date)::date as interaction_month,
    chatbot.channel,
    chatbot.language,
    chatbot.beneficiary_id,
    chatbot.mother_id,
    chatbot.child_id,
    chatbot.household_id,
    coalesce(chatbot.district, households.district) as district,
    coalesce(chatbot.state, households.state) as state,
    coalesce(chatbot.partner_ngo, households.partner_ngo) as partner_ngo,
    households.ward,
    households.area,
    chatbot.consent_given,
    chatbot.intent,
    chatbot.intent_confidence,
    chatbot.message_count,
    chatbot.first_response_seconds,
    chatbot.escalated_to_human,
    chatbot.escalation_reason,
    chatbot.handoff_worker_id,
    chatbot.linked_record_type,
    chatbot.linked_record_id,
    chatbot.resolution_status,
    chatbot.sentiment,
    chatbot.bot_version,
    chatbot.free_text_topic,
    chatbot.source_loaded_at
from {{ ref('stg_health__chatbot_interactions') }} as chatbot
left join {{ ref('dim_health_households') }} as households
    on chatbot.household_id = households.household_id
where not chatbot.is_duplicate_interaction_id
