select
    risk.maternal_risk_row_sk,
    risk.pregnancy_id,
    risk.visit_id,
    risk.mother_id,
    risk.beneficiary_id,
    risk.household_id,
    risk.field_worker_id,
    risk.mother_name,
    risk.visit_date,
    date_trunc('month', risk.visit_date)::date as visit_month,
    risk.lmp_date,
    risk.estimated_delivery_date,
    risk.next_visit_date,
    coalesce(risk.district, households.district) as district,
    coalesce(risk.state, households.state) as state,
    coalesce(risk.partner_ngo, households.partner_ngo) as partner_ngo,
    coalesce(risk.ward, households.ward) as ward,
    coalesce(risk.area, households.area) as area,
    risk.age_years,
    risk.gravida,
    risk.parity,
    risk.gestational_age_weeks,
    risk.hemoglobin_g_dl,
    risk.bp_systolic,
    risk.bp_diastolic,
    risk.bmi,
    risk.prior_c_section,
    risk.danger_signs,
    risk.anemia_status,
    risk.hypertension_flag,
    risk.risk_level,
    risk.is_high_risk,
    risk.referral_status,
    risk.is_referred,
    risk.referred_facility,
    risk.transport_support,
    risk.case_status,
    risk.source_loaded_at
from {{ ref('stg_health__maternal_mortality_risk') }} as risk
left join {{ ref('dim_health_households') }} as households
    on risk.household_id = households.household_id
where not risk.is_duplicate_visit_id
