name: dbt CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - main

jobs:
  dbt_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Create dbt profile
        run: |
          mkdir -p "$HOME/.dbt"
          cat <<EOF > "$HOME/.dbt/profiles.yml"
          health_demo:
            outputs:
              dev:
                type: postgres
                host: "{{ env_var('POSTGRES_HOST') }}"
                user: "{{ env_var('POSTGRES_USER') }}"
                password: "{{ env_var('POSTGRES_PASSWORD') }}"
                port: 5432
                dbname: "{{ env_var('POSTGRES_DBNAME') }}"
                schema: dev
                threads: 4
              prod:
                type: postgres
                host: "{{ env_var('POSTGRES_HOST') }}"
                user: "{{ env_var('POSTGRES_USER') }}"
                password: "{{ env_var('POSTGRES_PASSWORD') }}"
                port: 5432
                dbname: "{{ env_var('POSTGRES_DBNAME') }}"
                schema: prod
                threads: 4
            target: dev
          EOF

      - name: Install dbt dependencies
        run: dbt deps
        env:
          DBT_PROFILES_DIR: ~/.dbt

      - name: Build dbt project
        run: dbt build --select health_demo
        env:
          DBT_PROFILES_DIR: ~/.dbt
          POSTGRES_DBNAME: ${{ secrets.POSTGRES_DBNAME }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}

      - name: Lint models
        run: sqlfluff lint models -f human
        env:
          DBT_PROFILES_DIR: ~/.dbt
          POSTGRES_DBNAME: ${{ secrets.POSTGRES_DBNAME }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
